---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  labels:
    app: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
      - name: envoy
        image: dwoodworth414/jace:envoy-72acc8b87d279ac79dbde8f9131743502be553d3
        env:
        - name: ENVOY_UID
          value: "0"
        ports:
        - containerPort: 8080
        - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: envoy
spec:
  selector:
    app: envoy
  ports:
    - name: proxy
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: admin
      protocol: TCP
      port: 8081
      targetPort: 8081
  type: LoadBalancer
