FROM node 
RUN wget -O protoc-gen-grpc-web "https://github.com/grpc/grpc-web/releases/download/1.2.1/protoc-gen-grpc-web-1.2.1-linux-x86_64"
RUN mv protoc-gen-grpc-web /usr/local/bin
RUN chmod +x  /usr/local/bin/protoc-gen-grpc-web
RUN wget https://github.com/protocolbuffers/protobuf/releases/download/v3.13.0/protoc-3.13.0-linux-x86_64.zip
RUN unzip protoc-3.13.0-linux-x86_64.zip
RUN mv bin/protoc /usr/local/bin
RUN chmod +x /usr/local/bin/protoc

