FROM node 
RUN apt update
RUN wget -O protoc-gen-grpc-web "https://github.com/grpc/grpc-web/releases/download/1.2.1/protoc-gen-grpc-web-1.2.1-linux-x86_64"
RUN mv protoc-gen-grpc-web /usr/local/bin
RUN chmod +x  /usr/local/bin/protoc-gen-grpc-web
RUN apt install -y protobuf-compiler

